#define MAINPREFIX x
#define PREFIX TMF

#define MAJOR 1
#define MINOR 0
#define PATCH 6
#define BUILD 7

#define VERSION MAJOR.MINOR.PATCH
#define VERSION_AR MAJOR,MINOR,PATCH

#define REQUIRED_VERSION 2.18
