#define MAINPREFIX x
#define PREFIX TMF

#define MAJOR 1
#define MINOR 1
#define PATCH 0
#define BUILD 8

#define VERSION MAJOR.MINOR.PATCH
#define VERSION_AR MAJOR,MINOR,PATCH

#define REQUIRED_VERSION 2.18
