#define MAINPREFIX x
#define PREFIX TMF

#define MAJOR 1
#define MINOR 1
#define PATCH 1
#define BUILD 9

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR  MAJOR,MINOR,PATCH,BUILD

#define REQUIRED_VERSION 2.18
