[sqf.banned_commands]
options.ignore = [
    "addPublicVariableEventHandler", # Alt syntax is broken, main syntax ia ok
    "createSoundSource", # Greatly attenuated when in first person and in a vehicle
]
