name = "TMF"
prefix = "tmf"
author = "TMF & ARCOMM"
mainprefix = "x"

[files]
include = [
    "logo_tmf_ca.paa",
    "meta.cpp",
    "mod.cpp",
    "README.md",
]
exclude = [
    ".inc",
    ".inc.sqf",
]

[version]
major = 1
minor = 0
patch = 0
git_hash = 0
