name = "TMF"
prefix = "tmf"
author = "TMF & ARCOMM"
mainprefix = "x"

[files]
include = [
    "meta.cpp",
    "mod.cpp",
    "README.md",
]

[version]
major = 1
minor = 0
patch = 0

git_hash = 0

# Unused in HEMTT v1.11 or higher, kept for backwards compatibility
[asc]
enabled = true
exclude = [
    ".inc.sqf",
]
