#define COMPONENT autotest

#include "\x\tmf\addons\main\script_mod.hpp"
#include "\x\tmf\addons\main\script_macros.hpp"

#define AUTOTEST_PASS -1
#define AUTOTEST_ERROR 0
#define AUTOTEST_WARNING 1
#define AUTOTEST_MULTILINE 10

#define GLOBAL_COMMANDS [ \
"useaisteeringcomponent",              \
"unlinkitem",                          \
"unassignvehicle",                     \
"unassignitem",                        \
"synchronizeobjectsremove",            \
"synchronizeobjectsadd",               \
"switchmove",                          \
"switchgesture",                       \
"stop",                                \
"setwinddir",                          \
"setwind",                             \
"setwaypointvisible",                  \
"setwaypointspeed",                    \
"setwaypointformation",                \
"setwaypointbehaviour",                \
"setwaterleakiness",                   \
"setvelocitytransformation",           \
"setvelocitymodelspace",               \
"setvelocity",                         \
"setvehicleposition",                  \
"setvehiclelock",                      \
"setvehicleinit",                      \
"setvehiclecargo",                     \
"setvehiclearmor",                     \
"setvehicleammodef",                   \
"setvehicleammo",                      \
"setvectorup",                         \
"setvectordirandup",                   \
"setvectordir",                        \
"setunloadincombat",                   \
"setunittrait",                        \
"setunitrank",                         \
"setunitposweak",                      \
"setunitpos",                          \
"setunitloadout",                      \
"setunitfreefallheight",               \
"setunconscious",                      \
"setturretlimits",                     \
"settowparent",                        \
"settimemultiplier",                   \
"setterrainheight",                    \
"setspeedmode",                        \
"setskill",                            \
"setshotparents",                      \
"setrepaircargo",                      \
"setrank",                             \
"setrain",                             \
"setposworld",                         \
"setposatl",                           \
"setposaslw",                          \
"setposasl",                           \
"setpos",                              \
"setplatenumber",                      \
"setpilotlight",                       \
"setobjecttextureglobal",              \
"setobjectscale",                      \
"setobjectmaterialglobal",             \
"setmass",                             \
"setmarkertype",                       \
"setmarkertext",                       \
"setmarkersize",                       \
"setmarkershape",                      \
"setmarkershadow",                     \
"setmarkerpos",                        \
"setmarkerpolyline",                   \
"setmarkerdir",                        \
"setmarkercolor",                      \
"setmarkerbrush",                      \
"setmarkeralpha",                      \
"sethitpointdamage",                   \
"sethitindex",                         \
"sethit",                              \
"setgroupidglobal",                    \
"setfuelconsumptioncoef",              \
"setfuelcargo",                        \
"setfuel",                             \
"setfriend",                           \
"setformdir",                          \
"setformation",                        \
"setfog",                              \
"setflagtexture",                      \
"setflagside",                         \
"setflagowner",                        \
"setdir",                              \
"setdestination",                      \
"setdammage",                          \
"setdamage",                           \
"setcombatmode",                       \
"setcombatbehaviour",                  \
"setcollisionlight",                   \
"setcenterofmass",                     \
"setcaptive",                          \
"setbehaviourstrong",                  \
"setbehaviour",                        \
"setangularvelocitymodelspace",        \
"setangularvelocity",                  \
"setammocargo",                        \
"setammo",                             \
"servertime",                          \
"selectweapon",                        \
"selectplayer",                        \
"selectleader",                        \
"ropeunwind",                          \
"ropecreate",                          \
"respawnvehicle",                      \
"removeweaponturret",                  \
"removeweaponglobal",                  \
"removeweapon",                        \
"removevest",                          \
"removeuniform",                       \
"removesecondaryweaponitem",           \
"removeprimaryweaponitem",             \
"removempeventhandler",                \
"removemagazineturret",                \
"removemagazinesturret",               \
"removemagazineglobal",                \
"removeitems",                         \
"removeitemfromvest",                  \
"removeitemfromuniform",               \
"removeitemfrombackpack",              \
"removeitem",                          \
"removeheadgear",                      \
"removehandgunitem",                   \
"removegoggles",                       \
"removefromremainscollector",          \
"removebinocularitem",                 \
"removebackpackglobal",                \
"removebackpack",                      \
"removeallweapons",                    \
"removeallsecondaryweaponitems",       \
"removeallprimaryweaponitems",         \
"removeallmpeventhandlers",            \
"removeallitems",                      \
"removeallhandgunitems",               \
"removeallbinocularitems",             \
"removeallassigneditems",              \
"remotecontrol",                       \
"radiochannelcreate",                  \
"radiochanneladd",                     \
"publicvariable",                      \
"processinitcommands",                 \
"playsound3d",                         \
"playmovenow",                         \
"playmove",                            \
"playactionnow",                       \
"playaction",                          \
"ordergetin",                          \
"moveto",                              \
"moveout",                             \
"moveinturret",                        \
"moveingunner",                        \
"moveindriver",                        \
"moveincommander",                     \
"moveincargo",                         \
"moveinany",                           \
"move",                                \
"lockturret",                          \
"lockdriver",                          \
"lockcargo",                           \
"lock",                                \
"linkitem",                            \
"landat",                              \
"land",                                \
"kbtell",                              \
"joinsilent",                          \
"joinassilent",                        \
"joinas",                              \
"join",                                \
"islaseron",                           \
"inflame",                             \
"hideselection",                       \
"hideobjectglobal",                    \
"hidebody",                            \
"getvehiclecargo",                     \
"forgettarget",                        \
"forceweaponfire",                     \
"forcerespawn",                        \
"forcehitpointsdamagesync",            \
"forceflagtexture",                    \
"forceadduniform",                     \
"flyinheight",                         \
"flagowner",                           \
"fire",                                \
"estimatedtimeleft",                   \
"engineon",                            \
"enableweapondisassembly",             \
"enablestamina",                       \
"enablesimulationglobal",              \
"enableropeattach",                    \
"enableirlasers",                      \
"enablegunlights",                     \
"enablefatigue",                       \
"enablecollisionwith",                 \
"enableattack",                        \
"enableai",                            \
"dowatch",                             \
"dotarget",                            \
"dosuppressivefire",                   \
"dostop",                              \
"domove",                              \
"dogetout",                            \
"dofollow",                            \
"dofire",                              \
"disabletiequipment",                  \
"disablenvgequipment",                 \
"disablecollisionwith",                \
"disablebrakes",                       \
"disableai",                           \
"detach",                              \
"deletewaypoint",                      \
"deletevehiclecrew",                   \
"deletevehicle",                       \
"deletestatus",                        \
"deletemarker",                        \
"deletegroupwhenempty",                \
"deletegroup",                         \
"deletecenter",                        \
"createvehiclecrew",                   \
"createvehicle",                       \
"createunit",                          \
"createsoundsource",                   \
"createsimpleobject",                  \
"createmarker",                        \
"creategroup",                         \
"createcenter",                        \
"createagent",                         \
"connectterminaltouav",                \
"commandwatch",                        \
"commandtarget",                       \
"commandsuppressivefire",              \
"commandstop",                         \
"commandmove",                         \
"commandgetout",                       \
"clearweaponcargoglobal",              \
"clearmagazinecargoglobal",            \
"clearitemcargoglobal",                \
"clearbackpackcargoglobal",            \
"attachto",                            \
"assignteam",                          \
"assignitem",                          \
"assignasgunner",                      \
"assignasdriver",                      \
"assignascommander",                   \
"assignascargo",                       \
"animatesource",                       \
"animatedoor",                         \
"animate",                             \
"allowservice",                        \
"allowgetin",                          \
"allowfleeing",                        \
"allowdammage",                        \
"allowdamage",                         \
"allowcrewinimmobile",                 \
"addweaponwithattachmentscargoglobal", \
"addweaponturret",                     \
"addweaponitem",                       \
"addweaponglobal",                     \
"addweaponcargoglobal",                \
"addweapon",                           \
"addwaypoint",                         \
"addvest",                             \
"adduniform",                          \
"addtorque",                           \
"addtoremainscollector",               \
"addsecondaryweaponitem",              \
"addscoreside",                        \
"addscore",                            \
"addrating",                           \
"addprimaryweaponitem",                \
"addmpeventhandler",                   \
"addmagazineturret",                   \
"addmagazines",                        \
"addmagazineglobal",                   \
"addmagazinecargoglobal",              \
"addmagazineammocargo",                \
"additemtovest",                       \
"additemtouniform",                    \
"additemtobackpack",                   \
"additemcargoglobal",                  \
"additem",                             \
"addheadgear",                         \
"addhandgunitem",                      \
"addforce",                            \
"addbinocularitem",                    \
"addbackpackglobal",                   \
"addbackpackcargoglobal",              \
"addbackpack",                         \
"actionnow",                           \
"action"]
